container:
  image: node:latest
curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
check_task:
  node_modules_cache:
    folder: node_modules
    populate_script: npm install
  test_script: node indes.js
